project_id = "wwungotslsvanzyczwui"

[functions.scan-receipt]
verify_jwt = false

[functions.check-alarms-reminders]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.dismiss-alarm]
verify_jwt = false

[functions.process-recurring-bills]
verify_jwt = false
